# Currently the builds use @dataflake's Appveyor account.  The PyPI token belongs
# to zope.wheelbuilder, which is managed by @mgedmin and @dataflake.

environment:
  global:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD:
      secure: vSlDBj79vziJOA5k3z16r1OSr/7Jq6uCf23VKErSsXWb2dGJMUxR6GQ6tRs53GfiyxBQdpdfOA5QuVS4G4W3rVLwD/YXCidpidwBF3pKk4J2Nnk88HpZID6lQOV713DA/kkEuoO97Ty1BRYeaca9bA0P0KmRYU7Iy30p4xBUnmNKYnfilH0/waASYEDwpkrl49DiUh1+bMQjE5LKIBeaF0LLquzHGYETQf4BgpywUIV/8dQnc0vL/RXCa6PrWOxg/8S6ponIYyJ32Y4OoprZ1Q==

  matrix:
    - python: 27
    - python: 27-x64
    - python: 35
    - python: 35-x64
    - python: 36
    - python: 36-x64
    - python: 37
    - python: 37-x64
    - python: 38
    - python: 38-x64
    - python: 39
    - python: 39-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - pip install zc.buildout zope.testrunner
  - pip install -e .

build_script:
  - pip install wheel
  - python -W ignore setup.py -q bdist_wheel

test_script:
   - buildout
   - bin\test.exe

artifacts:
  - path: 'dist\*.whl'
    name: wheel

deploy_script:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist\*.whl }

deploy: on
